name: Generate Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            images/snake.svg?color_snake=#179299
            images/snake-dark.svg?palette=github-dark&color_snake=#179299

      - name: Push SVG to Branch 'main'
        run: |
          git config user.name "Roberto Schiavone"
          git config user.email "5054879+robertoschiavone@users.noreply.github.com"
          git add images/snake.svg images/snake-dark.svg
          git commit --m "chore: update snake"
          git push origin main
